from app.models.rol_model import Rol
from app.models.usuario_model import Usuario
from app.models.categoria_model import Categoria
from app.models.proveedor_model import Proveedor
from app.models.producto_model import Producto
from app.models.cliente_model import Cliente
from app.models.venta_model import Venta
from app.models.detalle_venta_model import DetalleVenta
from app.models.movimiento_inventario_model import MovimientoInventario